// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID        uuid.UUID
	Title     string
	Author    string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

type BookBorrow struct {
	ID         uuid.UUID
	IssuedAt   time.Time
	ReturnedAt sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
	BookID     uuid.UUID
	BorrowerID uuid.UUID
}

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserSubscriber struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       uuid.UUID
	SubscriberID uuid.UUID
}
