// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_subscribers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserSubscriber = `-- name: CreateUserSubscriber :one
INSERT INTO user_subscribers (id, created_at, updated_at, user_id, subscriber_id)
VALUES ($1, NOW(), NOW(), $2, $3)
RETURNING id, created_at, updated_at, user_id, subscriber_id
`

type CreateUserSubscriberParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	SubscriberID uuid.UUID
}

func (q *Queries) CreateUserSubscriber(ctx context.Context, arg CreateUserSubscriberParams) (UserSubscriber, error) {
	row := q.db.QueryRowContext(ctx, createUserSubscriber, arg.ID, arg.UserID, arg.SubscriberID)
	var i UserSubscriber
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.SubscriberID,
	)
	return i, err
}
